# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MLFA <- function(nb_composantes, nb_facteur, X, Y, Z, id, Lam, beta, tau, s_e, s_b, max_it, pro2, nb_sujet, J, p, fixed_factor) {
    .Call(`_MixLFA_MLFA`, nb_composantes, nb_facteur, X, Y, Z, id, Lam, beta, tau, s_e, s_b, max_it, pro2, nb_sujet, J, p, fixed_factor)
}

